// This file is auto-generated by @hey-api/openapi-ts

export const AddCategoriesRequestSchema = {
    properties: {
        category_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Category Ids'
        }
    },
    type: 'object',
    required: ['category_ids'],
    title: 'AddCategoriesRequest',
    description: 'Request body for adding categories to an item.'
} as const;

export const ArchivedItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        price_cents: {
            type: 'integer',
            minimum: 0,
            title: 'Price Cents'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        product_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Url'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        added_at: {
            type: 'string',
            format: 'date-time',
            title: 'Added At'
        },
        status: {
            type: 'string',
            const: 'archived',
            title: 'Status'
        },
        archived_at: {
            type: 'string',
            format: 'date-time',
            title: 'Archived At'
        },
        is_most_desired: {
            type: 'boolean',
            title: 'Is Most Desired',
            default: false
        },
        categories: {
            items: {
                '$ref': '#/components/schemas/CategoryPublic'
            },
            type: 'array',
            title: 'Categories',
            default: []
        }
    },
    type: 'object',
    required: ['title', 'price_cents', 'id', 'owner_id', 'added_at', 'status', 'archived_at'],
    title: 'ArchivedItemPublic',
    description: 'API response for an archived item.'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const BudgetPublicSchema = {
    properties: {
        cents_at_last_update: {
            type: 'integer',
            title: 'Cents At Last Update',
            default: 0
        },
        monthly_rate_cents: {
            type: 'integer',
            minimum: 0,
            title: 'Monthly Rate Cents',
            default: 60000
        },
        freeze_until: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Freeze Until'
        },
        stashed_monthly_rate_cents: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stashed Monthly Rate Cents'
        },
        freeze_penalty_days: {
            type: 'integer',
            minimum: 0,
            title: 'Freeze Penalty Days',
            default: 7
        },
        cooloff_scaling_cents: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cooloff Scaling Cents'
        },
        cooloff_scaling_days: {
            type: 'integer',
            minimum: 0,
            title: 'Cooloff Scaling Days',
            default: 3
        },
        cooloff_min_threshold_cents: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cooloff Min Threshold Cents'
        },
        cooloff_min_threshold_days: {
            type: 'integer',
            minimum: 0,
            title: 'Cooloff Min Threshold Days',
            default: 7
        },
        cooloff_base_days: {
            type: 'integer',
            minimum: 0,
            title: 'Cooloff Base Days',
            default: 0
        },
        cooloff_max_days: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cooloff Max Days'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        last_updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Last Updated At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'last_updated_at'],
    title: 'BudgetPublic',
    description: 'Budget response - client calculates current value from rate + timestamp.'
} as const;

export const BudgetUpdateSchema = {
    properties: {
        cents_at_last_update: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cents At Last Update'
        },
        monthly_rate_cents: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Monthly Rate Cents'
        },
        freeze_until: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Freeze Until'
        },
        stashed_monthly_rate_cents: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stashed Monthly Rate Cents'
        },
        freeze_penalty_days: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Freeze Penalty Days'
        },
        cooloff_scaling_cents: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cooloff Scaling Cents'
        },
        cooloff_scaling_days: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cooloff Scaling Days'
        },
        cooloff_min_threshold_cents: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cooloff Min Threshold Cents'
        },
        cooloff_min_threshold_days: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cooloff Min Threshold Days'
        },
        cooloff_base_days: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cooloff Base Days'
        },
        cooloff_max_days: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cooloff Max Days'
        }
    },
    type: 'object',
    title: 'BudgetUpdate',
    description: 'Properties to receive on budget update.'
} as const;

export const BulkArchiveRequestSchema = {
    properties: {
        item_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            minItems: 1,
            title: 'Item Ids'
        }
    },
    type: 'object',
    required: ['item_ids'],
    title: 'BulkArchiveRequest',
    description: 'Request to archive multiple items at once.'
} as const;

export const BulkArchiveResponseSchema = {
    properties: {
        archived_count: {
            type: 'integer',
            title: 'Archived Count'
        }
    },
    type: 'object',
    required: ['archived_count'],
    title: 'BulkArchiveResponse',
    description: 'Response for bulk archive operation.'
} as const;

export const BulkDeleteRequestSchema = {
    properties: {
        item_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            minItems: 1,
            title: 'Item Ids'
        }
    },
    type: 'object',
    required: ['item_ids'],
    title: 'BulkDeleteRequest',
    description: 'Request to delete multiple items at once.'
} as const;

export const BulkDeleteResponseSchema = {
    properties: {
        deleted_count: {
            type: 'integer',
            title: 'Deleted Count'
        }
    },
    type: 'object',
    required: ['deleted_count'],
    title: 'BulkDeleteResponse',
    description: 'Response for bulk delete operation.'
} as const;

export const BulkSetCategoriesRequestSchema = {
    properties: {
        item_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            minItems: 1,
            title: 'Item Ids'
        },
        category_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Category Ids'
        }
    },
    type: 'object',
    required: ['item_ids'],
    title: 'BulkSetCategoriesRequest',
    description: 'Request to set categories on multiple items at once.'
} as const;

export const BulkSetCategoriesResponseSchema = {
    properties: {
        updated_count: {
            type: 'integer',
            title: 'Updated Count'
        }
    },
    type: 'object',
    required: ['updated_count'],
    title: 'BulkSetCategoriesResponse',
    description: 'Response for bulk set categories operation.'
} as const;

export const BulkUnarchiveResponseSchema = {
    properties: {
        unarchived_count: {
            type: 'integer',
            title: 'Unarchived Count'
        }
    },
    type: 'object',
    required: ['unarchived_count'],
    title: 'BulkUnarchiveResponse',
    description: 'Response for bulk unarchive operation.'
} as const;

export const CategoriesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CategoryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CategoriesPublic',
    description: 'List of categories.'
} as const;

export const CategoryCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CategoryCreate',
    description: 'Properties to receive on category creation.'
} as const;

export const CategoryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'parent_id', 'created_at'],
    title: 'CategoryPublic',
    description: 'API response for a category.'
} as const;

export const CategorySuggestionPublicSchema = {
    properties: {
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        },
        category_name: {
            type: 'string',
            title: 'Category Name'
        },
        confidence: {
            type: 'number',
            title: 'Confidence'
        },
        source: {
            type: 'string',
            title: 'Source'
        }
    },
    type: 'object',
    required: ['category_id', 'category_name', 'confidence', 'source'],
    title: 'CategorySuggestionPublic',
    description: 'A suggested category.'
} as const;

export const CategorySuggestionRequestSchema = {
    properties: {
        product_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Url'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        breadcrumbs: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Breadcrumbs'
        },
        brand: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        }
    },
    type: 'object',
    title: 'CategorySuggestionRequest',
    description: 'Request for category suggestions.'
} as const;

export const CategorySuggestionsPublicSchema = {
    properties: {
        suggestions: {
            items: {
                '$ref': '#/components/schemas/CategorySuggestionPublic'
            },
            type: 'array',
            title: 'Suggestions'
        }
    },
    type: 'object',
    required: ['suggestions'],
    title: 'CategorySuggestionsPublic',
    description: 'Response for category suggestions.'
} as const;

export const CategoryUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        }
    },
    type: 'object',
    title: 'CategoryUpdate',
    description: 'Properties to receive on category update.'
} as const;

export const CooloffSettingsPublicSchema = {
    properties: {
        cooloff_scaling_cents: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cooloff Scaling Cents'
        },
        cooloff_scaling_days: {
            type: 'integer',
            title: 'Cooloff Scaling Days',
            default: 3
        },
        cooloff_min_threshold_cents: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cooloff Min Threshold Cents'
        },
        cooloff_min_threshold_days: {
            type: 'integer',
            title: 'Cooloff Min Threshold Days',
            default: 7
        },
        cooloff_base_days: {
            type: 'integer',
            title: 'Cooloff Base Days',
            default: 0
        },
        cooloff_max_days: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cooloff Max Days'
        },
        freeze_penalty_days: {
            type: 'integer',
            title: 'Freeze Penalty Days',
            default: 7
        }
    },
    type: 'object',
    title: 'CooloffSettingsPublic',
    description: `Public cooloff settings for viewing shared wishlists.

Exposes only timing settings, not balance or rate info.`
} as const;

export const DeliveryStatusSchema = {
    type: 'string',
    enum: ['not_found', 'info_received', 'in_transit', 'out_for_delivery', 'delivered', 'exception', 'expired'],
    title: 'DeliveryStatus',
    description: 'Normalized delivery status from 17track.'
} as const;

export const GiftRequestSchema = {
    properties: {
        gift_message: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gift Message'
        },
        gifter_display_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gifter Display Name'
        },
        tracking_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Url'
        }
    },
    type: 'object',
    title: 'GiftRequest',
    description: 'Data when gifting an item to someone.'
} as const;

export const GiftedItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        price_cents: {
            type: 'integer',
            minimum: 0,
            title: 'Price Cents'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        product_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Url'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        added_at: {
            type: 'string',
            format: 'date-time',
            title: 'Added At'
        },
        status: {
            type: 'string',
            const: 'gifted',
            title: 'Status'
        },
        gifted_at: {
            type: 'string',
            format: 'date-time',
            title: 'Gifted At'
        },
        bought_by_id: {
            type: 'string',
            format: 'uuid',
            title: 'Bought By Id'
        },
        gifter_display_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gifter Display Name'
        },
        gift_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gift Message'
        },
        tracking_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Url'
        },
        is_most_desired: {
            type: 'boolean',
            title: 'Is Most Desired',
            default: false
        },
        categories: {
            items: {
                '$ref': '#/components/schemas/CategoryPublic'
            },
            type: 'array',
            title: 'Categories',
            default: []
        },
        tracking_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Number'
        },
        tracking_carrier: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Carrier'
        },
        estimated_delivery_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Estimated Delivery At'
        },
        tracking_synced_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Synced At'
        },
        tracking_status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DeliveryStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        tracking_status_label: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Status Label'
        },
        tracking_events: {
            items: {
                '$ref': '#/components/schemas/TrackingEventPublic'
            },
            type: 'array',
            title: 'Tracking Events',
            default: []
        }
    },
    type: 'object',
    required: ['title', 'price_cents', 'id', 'owner_id', 'added_at', 'status', 'gifted_at', 'bought_by_id'],
    title: 'GiftedItemPublic',
    description: 'API response for a gifted item.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message',
    description: 'Generic message response.'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword',
    description: 'Request body for password reset.'
} as const;

export const NotificationPublicSchema = {
    properties: {
        notification_type: {
            '$ref': '#/components/schemas/NotificationType'
        },
        title: {
            type: 'string',
            maxLength: 200,
            title: 'Title'
        },
        message: {
            type: 'string',
            maxLength: 500,
            title: 'Message'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        read_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Read At'
        },
        payload: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payload'
        }
    },
    type: 'object',
    required: ['notification_type', 'title', 'message', 'id', 'user_id', 'created_at', 'read_at'],
    title: 'NotificationPublic',
    description: 'API response for a notification.'
} as const;

export const NotificationTypeSchema = {
    type: 'string',
    enum: ['gift_received', 'thank_you', 'freeze_expiring', 'budget_milestone', 'delivery_info_received', 'delivery_in_transit', 'delivery_out_for_delivery', 'delivery_delivered', 'delivery_exception', 'delivery_expired', 'price_drop', 'price_increase', 'price_tracking_paused'],
    title: 'NotificationType',
    description: 'Types of notifications.'
} as const;

export const NotificationsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/NotificationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        unread_count: {
            type: 'integer',
            title: 'Unread Count'
        }
    },
    type: 'object',
    required: ['data', 'count', 'unread_count'],
    title: 'NotificationsPublic',
    description: 'Paginated list of notifications.'
} as const;

export const ParseUrlRequestSchema = {
    properties: {
        url: {
            type: 'string',
            maxLength: 2083,
            minLength: 1,
            format: 'uri',
            title: 'Url'
        }
    },
    type: 'object',
    required: ['url'],
    title: 'ParseUrlRequest',
    description: 'Request body for URL parsing endpoint.'
} as const;

export const ParseUrlResponseSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        price_cents: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Cents'
        },
        currency: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Currency'
        },
        source_url: {
            type: 'string',
            title: 'Source Url'
        },
        final_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Final Url'
        },
        extraction_method: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extraction Method'
        },
        brand: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        breadcrumbs: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Breadcrumbs'
        }
    },
    type: 'object',
    required: ['source_url'],
    title: 'ParseUrlResponse',
    description: 'Response from URL parsing endpoint.'
} as const;

export const PrepopulateResponseSchema = {
    properties: {
        items_created: {
            type: 'integer',
            title: 'Items Created'
        },
        categories_created: {
            type: 'integer',
            title: 'Categories Created'
        },
        budget_set: {
            type: 'boolean',
            title: 'Budget Set'
        },
        test_user_created: {
            type: 'boolean',
            title: 'Test User Created'
        },
        test_user_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Test User Id'
        },
        errors: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Errors'
        }
    },
    type: 'object',
    required: ['items_created', 'categories_created', 'budget_set', 'test_user_created', 'test_user_id', 'errors'],
    title: 'PrepopulateResponse'
} as const;

export const PriceCheckFailureReasonSchema = {
    type: 'string',
    enum: ['blocked', 'unreachable', 'no_price', 'link_moved', 'different_product', 'implausible', 'no_link'],
    title: 'PriceCheckFailureReason',
    description: 'Why a check could not be trusted. Drives the one-word UI status.'
} as const;

export const PriceCheckOutcomeSchema = {
    type: 'string',
    enum: ['unchanged', 'dropped', 'increased', 'failed'],
    title: 'PriceCheckOutcome',
    description: 'Result of a single price check.'
} as const;

export const PriceCheckResultPublicSchema = {
    properties: {
        outcome: {
            '$ref': '#/components/schemas/PriceCheckOutcome'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        reason: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PriceCheckFailureReason'
                },
                {
                    type: 'null'
                }
            ]
        },
        checked_at: {
            type: 'string',
            format: 'date-time',
            title: 'Checked At'
        },
        price_cents: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Cents'
        },
        previous_price_cents: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Previous Price Cents'
        },
        tracking: {
            '$ref': '#/components/schemas/PriceTrackingPublic'
        }
    },
    type: 'object',
    required: ['outcome', 'message', 'checked_at', 'tracking'],
    title: 'PriceCheckResultPublic',
    description: `Response for a manual price check.

Failures are reported inside the body (not as HTTP errors) so the UI can
show them inline next to the graph rather than as a generic error toast.`
} as const;

export const PriceHistoryPublicSchema = {
    properties: {
        item_id: {
            type: 'string',
            format: 'uuid',
            title: 'Item Id'
        },
        current_price_cents: {
            type: 'integer',
            title: 'Current Price Cents'
        },
        tracking: {
            '$ref': '#/components/schemas/PriceTrackingPublic'
        },
        points: {
            items: {
                '$ref': '#/components/schemas/PricePointPublic'
            },
            type: 'array',
            title: 'Points'
        }
    },
    type: 'object',
    required: ['item_id', 'current_price_cents', 'tracking', 'points'],
    title: 'PriceHistoryPublic',
    description: 'Full price history for one item (drawer graph).'
} as const;

export const PricePointPublicSchema = {
    properties: {
        recorded_at: {
            type: 'string',
            format: 'date-time',
            title: 'Recorded At'
        },
        price_cents: {
            type: 'integer',
            title: 'Price Cents'
        },
        source: {
            '$ref': '#/components/schemas/PricePointSource'
        }
    },
    type: 'object',
    required: ['recorded_at', 'price_cents', 'source'],
    title: 'PricePointPublic',
    description: 'A single point on the price history graph.'
} as const;

export const PricePointSourceSchema = {
    type: 'string',
    enum: ['initial', 'scheduled', 'manual', 'added'],
    title: 'PricePointSource',
    description: 'How a price point was captured.'
} as const;

export const PriceTrackingPublicSchema = {
    properties: {
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        },
        eligible: {
            type: 'boolean',
            title: 'Eligible'
        },
        paused: {
            type: 'boolean',
            title: 'Paused'
        },
        disabled_by_user: {
            type: 'boolean',
            title: 'Disabled By User',
            default: false
        },
        last_checked_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Checked At'
        },
        last_error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Error'
        },
        last_error_reason: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PriceCheckFailureReason'
                },
                {
                    type: 'null'
                }
            ]
        },
        consecutive_failures: {
            type: 'integer',
            title: 'Consecutive Failures',
            default: 0
        },
        original_price_cents: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Original Price Cents'
        },
        lowest_price_cents: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lowest Price Cents'
        },
        previous_price_cents: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Previous Price Cents'
        },
        price_changed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Changed At'
        }
    },
    type: 'object',
    required: ['enabled', 'eligible', 'paused'],
    title: 'PriceTrackingPublic',
    description: 'Tracking state embedded in wishlisted item responses.'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const PurchaseRequestSchema = {
    properties: {
        tracking_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Url'
        },
        actual_price_paid_cents: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actual Price Paid Cents'
        },
        tracking_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Number'
        },
        tracking_carrier: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Carrier'
        }
    },
    type: 'object',
    title: 'PurchaseRequest',
    description: 'Optional data when marking item as purchased.'
} as const;

export const PurchasedItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        price_cents: {
            type: 'integer',
            minimum: 0,
            title: 'Price Cents'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        product_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Url'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        added_at: {
            type: 'string',
            format: 'date-time',
            title: 'Added At'
        },
        status: {
            type: 'string',
            const: 'purchased',
            title: 'Status'
        },
        purchased_at: {
            type: 'string',
            format: 'date-time',
            title: 'Purchased At'
        },
        is_most_desired: {
            type: 'boolean',
            title: 'Is Most Desired',
            default: false
        },
        categories: {
            items: {
                '$ref': '#/components/schemas/CategoryPublic'
            },
            type: 'array',
            title: 'Categories',
            default: []
        },
        tracking_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Url'
        },
        actual_price_paid_cents: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actual Price Paid Cents'
        },
        tracking_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Number'
        },
        tracking_carrier: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Carrier'
        },
        estimated_delivery_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Estimated Delivery At'
        },
        tracking_synced_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Synced At'
        },
        tracking_status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DeliveryStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        tracking_status_label: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Status Label'
        },
        tracking_events: {
            items: {
                '$ref': '#/components/schemas/TrackingEventPublic'
            },
            type: 'array',
            title: 'Tracking Events',
            default: []
        }
    },
    type: 'object',
    required: ['title', 'price_cents', 'id', 'owner_id', 'added_at', 'status', 'purchased_at'],
    title: 'PurchasedItemPublic',
    description: 'API response for a purchased item.'
} as const;

export const PushSubscriptionCreateSchema = {
    properties: {
        endpoint: {
            type: 'string',
            maxLength: 500,
            title: 'Endpoint'
        },
        p256dh_key: {
            type: 'string',
            maxLength: 200,
            title: 'P256Dh Key'
        },
        auth_key: {
            type: 'string',
            maxLength: 50,
            title: 'Auth Key'
        }
    },
    type: 'object',
    required: ['endpoint', 'p256dh_key', 'auth_key'],
    title: 'PushSubscriptionCreate',
    description: 'Properties to receive on push subscription creation.'
} as const;

export const PushSubscriptionPublicSchema = {
    properties: {
        endpoint: {
            type: 'string',
            maxLength: 500,
            title: 'Endpoint'
        },
        p256dh_key: {
            type: 'string',
            maxLength: 200,
            title: 'P256Dh Key'
        },
        auth_key: {
            type: 'string',
            maxLength: 50,
            title: 'Auth Key'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['endpoint', 'p256dh_key', 'auth_key', 'id', 'created_at'],
    title: 'PushSubscriptionPublic',
    description: 'API response for a push subscription.'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token',
    description: 'JSON payload containing access token.'
} as const;

export const TrackedItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        price_cents: {
            type: 'integer',
            minimum: 0,
            title: 'Price Cents'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        product_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Url'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        added_at: {
            type: 'string',
            format: 'date-time',
            title: 'Added At'
        },
        status: {
            type: 'string',
            const: 'tracking',
            title: 'Status'
        },
        is_most_desired: {
            type: 'boolean',
            title: 'Is Most Desired',
            default: false
        },
        categories: {
            items: {
                '$ref': '#/components/schemas/CategoryPublic'
            },
            type: 'array',
            title: 'Categories',
            default: []
        },
        tracking_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Number'
        },
        tracking_carrier: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Carrier'
        },
        tracking_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Url'
        },
        estimated_delivery_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Estimated Delivery At'
        },
        tracking_synced_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Synced At'
        },
        tracking_status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DeliveryStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        tracking_status_label: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Status Label'
        },
        tracking_events: {
            items: {
                '$ref': '#/components/schemas/TrackingEventPublic'
            },
            type: 'array',
            title: 'Tracking Events',
            default: []
        }
    },
    type: 'object',
    required: ['title', 'price_cents', 'id', 'owner_id', 'added_at', 'status'],
    title: 'TrackedItemPublic',
    description: 'API response for a tracked item (not from wishlist).'
} as const;

export const TrackingAddressSchema = {
    properties: {
        country: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        state: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'State'
        },
        city: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        postal_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Postal Code'
        }
    },
    type: 'object',
    title: 'TrackingAddress',
    description: 'Address information from tracking event.'
} as const;

export const TrackingEventSchema = {
    properties: {
        time_iso: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Time Iso'
        },
        time_utc: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Time Utc'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        location: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location'
        },
        stage: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stage'
        },
        sub_status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sub Status'
        },
        address: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/TrackingAddress'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['description'],
    title: 'TrackingEvent',
    description: 'Single tracking event from carrier.'
} as const;

export const TrackingEventPublicSchema = {
    properties: {
        timestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Timestamp'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        location: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location'
        }
    },
    type: 'object',
    required: ['description'],
    title: 'TrackingEventPublic',
    description: 'Simplified tracking event for public API responses.'
} as const;

export const TrackingParseRequestSchema = {
    properties: {
        input: {
            type: 'string',
            maxLength: 2048,
            minLength: 1,
            title: 'Input'
        }
    },
    type: 'object',
    required: ['input'],
    title: 'TrackingParseRequest',
    description: 'Request to parse a tracking number or URL.'
} as const;

export const TrackingParseResponseSchema = {
    properties: {
        tracking_number: {
            type: 'string',
            title: 'Tracking Number'
        },
        carrier: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Carrier'
        },
        carrier_code: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Carrier Code'
        },
        is_valid: {
            type: 'boolean',
            title: 'Is Valid'
        },
        tracking_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Url'
        }
    },
    type: 'object',
    required: ['tracking_number', 'is_valid'],
    title: 'TrackingParseResponse',
    description: 'Response from parsing a tracking input.'
} as const;

export const TrackingStatusPublicSchema = {
    properties: {
        tracking_number: {
            type: 'string',
            title: 'Tracking Number'
        },
        carrier: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Carrier'
        },
        status: {
            '$ref': '#/components/schemas/DeliveryStatus'
        },
        status_label: {
            type: 'string',
            title: 'Status Label'
        },
        estimated_delivery_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Estimated Delivery At'
        },
        latest_event_description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Event Description'
        },
        latest_event_location: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Event Location'
        },
        latest_event_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Event At'
        },
        events: {
            items: {
                '$ref': '#/components/schemas/TrackingEvent'
            },
            type: 'array',
            title: 'Events'
        },
        synced_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Synced At'
        }
    },
    type: 'object',
    required: ['tracking_number', 'status', 'status_label'],
    title: 'TrackingStatusPublic',
    description: 'Public tracking status for API responses.'
} as const;

export const TrackingSyncResponseSchema = {
    properties: {
        synced_count: {
            type: 'integer',
            title: 'Synced Count'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['synced_count', 'message'],
    title: 'TrackingSyncResponse',
    description: 'Response from sync all tracking operation.'
} as const;

export const UndoDestinationSchema = {
    type: 'string',
    enum: ['wishlist', 'archive'],
    title: 'UndoDestination',
    description: 'Where to move an item when undoing purchase/gift.'
} as const;

export const UndoRequestSchema = {
    properties: {
        destination: {
            '$ref': '#/components/schemas/UndoDestination',
            description: 'Where to move the item: wishlist or archive',
            default: 'wishlist'
        },
        refund_cents: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Refund Cents',
            description: 'Amount to refund. None = item price, 0 = no refund, or specify amount'
        },
        reason: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        }
    },
    type: 'object',
    title: 'UndoRequest',
    description: `Unified request to undo a purchase or gift.

Supports flexible handling:
- Choose destination (wishlist or archive)
- Specify refund amount (None = item price, 0 = no refund, or custom amount)`
} as const;

export const UnreadCountPublicSchema = {
    properties: {
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['count'],
    title: 'UnreadCountPublic',
    description: 'Response for unread notification count.'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword',
    description: 'Request body for password update.'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        wishlist_visibility: {
            '$ref': '#/components/schemas/WishlistVisibility',
            default: 'private'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate',
    description: 'Properties to receive via API on creation.'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        wishlist_visibility: {
            '$ref': '#/components/schemas/WishlistVisibility',
            default: 'private'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic',
    description: 'User response model for API.'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister',
    description: 'Properties for user self-registration.'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        wishlist_visibility: {
            '$ref': '#/components/schemas/WishlistVisibility',
            default: 'private'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate',
    description: 'Properties to receive via API on update, all are optional.'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        wishlist_visibility: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/WishlistVisibility'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'UserUpdateMe',
    description: 'Properties for user to update their own profile.'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic',
    description: 'Paginated list of users.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VapidKeyPublicSchema = {
    properties: {
        public_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Public Key'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        }
    },
    type: 'object',
    required: ['public_key', 'enabled'],
    title: 'VapidKeyPublic',
    description: 'API response for VAPID public key.'
} as const;

export const WaiveCooldownRequestSchema = {
    properties: {
        reason: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Reason'
        }
    },
    type: 'object',
    required: ['reason'],
    title: 'WaiveCooldownRequest',
    description: 'Request to waive cooldown period on a wishlist item.'
} as const;

export const WishlistItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        price_cents: {
            type: 'integer',
            minimum: 0,
            title: 'Price Cents'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        product_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Url'
        },
        category_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Category Ids'
        },
        tracking_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Number'
        },
        tracking_carrier: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Carrier'
        },
        tracking_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Url'
        },
        price_from_url: {
            type: 'boolean',
            title: 'Price From Url',
            default: false
        }
    },
    type: 'object',
    required: ['title', 'price_cents'],
    title: 'WishlistItemCreate',
    description: 'Properties to receive on wishlist item creation.'
} as const;

export const WishlistItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        price_cents: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Cents'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        product_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Url'
        },
        category_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        format: 'uuid'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Ids'
        },
        tracking_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Number'
        },
        tracking_carrier: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Carrier'
        },
        tracking_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking Url'
        }
    },
    type: 'object',
    title: 'WishlistItemUpdate',
    description: 'Properties to receive on wishlist item update.'
} as const;

export const WishlistItemsPublicSchema = {
    properties: {
        data: {
            items: {
                anyOf: [
                    {
                        '$ref': '#/components/schemas/WishlistedItemPublic'
                    },
                    {
                        '$ref': '#/components/schemas/PurchasedItemPublic'
                    },
                    {
                        '$ref': '#/components/schemas/GiftedItemPublic'
                    },
                    {
                        '$ref': '#/components/schemas/ArchivedItemPublic'
                    },
                    {
                        '$ref': '#/components/schemas/TrackedItemPublic'
                    }
                ]
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WishlistItemsPublic',
    description: 'Paginated list of wishlist items.'
} as const;

export const WishlistShareCreateSchema = {
    properties: {
        shared_with_email: {
            type: 'string',
            maxLength: 255,
            title: 'Shared With Email'
        }
    },
    type: 'object',
    required: ['shared_with_email'],
    title: 'WishlistShareCreate',
    description: 'Properties to receive on wishlist share creation.'
} as const;

export const WishlistSharePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        shared_with_id: {
            type: 'string',
            format: 'uuid',
            title: 'Shared With Id'
        },
        shared_with_email: {
            type: 'string',
            title: 'Shared With Email'
        },
        owner_email: {
            type: 'string',
            title: 'Owner Email'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'owner_id', 'shared_with_id', 'shared_with_email', 'owner_email', 'created_at'],
    title: 'WishlistSharePublic',
    description: 'API response for a wishlist share.'
} as const;

export const WishlistSharesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WishlistSharePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WishlistSharesPublic',
    description: 'Paginated list of wishlist shares.'
} as const;

export const WishlistVisibilitySchema = {
    type: 'string',
    enum: ['private', 'public'],
    title: 'WishlistVisibility',
    description: "Visibility setting for a user's wishlist."
} as const;

export const WishlistWithSettingsPublicSchema = {
    properties: {
        data: {
            items: {
                anyOf: [
                    {
                        '$ref': '#/components/schemas/WishlistedItemPublic'
                    },
                    {
                        '$ref': '#/components/schemas/PurchasedItemPublic'
                    },
                    {
                        '$ref': '#/components/schemas/GiftedItemPublic'
                    },
                    {
                        '$ref': '#/components/schemas/ArchivedItemPublic'
                    },
                    {
                        '$ref': '#/components/schemas/TrackedItemPublic'
                    }
                ]
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        owner_cooloff_settings: {
            '$ref': '#/components/schemas/CooloffSettingsPublic'
        }
    },
    type: 'object',
    required: ['data', 'count', 'owner_cooloff_settings'],
    title: 'WishlistWithSettingsPublic',
    description: "Wishlist items with owner's cooloff settings for shared wishlist viewing."
} as const;

export const WishlistedItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        price_cents: {
            type: 'integer',
            minimum: 0,
            title: 'Price Cents'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        product_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Url'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        added_at: {
            type: 'string',
            format: 'date-time',
            title: 'Added At'
        },
        status: {
            type: 'string',
            const: 'wishlisted',
            title: 'Status'
        },
        is_most_desired: {
            type: 'boolean',
            title: 'Is Most Desired',
            default: false
        },
        categories: {
            items: {
                '$ref': '#/components/schemas/CategoryPublic'
            },
            type: 'array',
            title: 'Categories',
            default: []
        },
        cooldown_waived_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cooldown Waived At'
        },
        price_tracking: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PriceTrackingPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['title', 'price_cents', 'id', 'owner_id', 'added_at', 'status'],
    title: 'WishlistedItemPublic',
    description: 'API response for a wishlisted item.'
} as const;