// This file is auto-generated by @hey-api/openapi-ts

/**
 * Request body for adding categories to an item.
 */
export type AddCategoriesRequest = {
    category_ids: Array<(string)>;
};

/**
 * API response for an archived item.
 */
export type ArchivedItemPublic = {
    title: string;
    description?: (string | null);
    price_cents: number;
    image_url?: (string | null);
    product_url?: (string | null);
    id: string;
    owner_id: string;
    added_at: string;
    status: "archived";
    archived_at: string;
    is_most_desired?: boolean;
    categories?: Array<CategoryPublic>;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Budget response - client calculates current value from rate + timestamp.
 */
export type BudgetPublic = {
    cents_at_last_update?: number;
    monthly_rate_cents?: number;
    freeze_until?: (string | null);
    stashed_monthly_rate_cents?: (number | null);
    freeze_penalty_days?: number;
    cooloff_scaling_cents?: (number | null);
    cooloff_scaling_days?: number;
    cooloff_min_threshold_cents?: (number | null);
    cooloff_min_threshold_days?: number;
    cooloff_base_days?: number;
    cooloff_max_days?: (number | null);
    id: string;
    user_id: string;
    last_updated_at: string;
};

/**
 * Properties to receive on budget update.
 */
export type BudgetUpdate = {
    cents_at_last_update?: (number | null);
    monthly_rate_cents?: (number | null);
    freeze_until?: (string | null);
    stashed_monthly_rate_cents?: (number | null);
    freeze_penalty_days?: (number | null);
    cooloff_scaling_cents?: (number | null);
    cooloff_scaling_days?: (number | null);
    cooloff_min_threshold_cents?: (number | null);
    cooloff_min_threshold_days?: (number | null);
    cooloff_base_days?: (number | null);
    cooloff_max_days?: (number | null);
};

/**
 * Request to archive multiple items at once.
 */
export type BulkArchiveRequest = {
    item_ids: Array<(string)>;
};

/**
 * Response for bulk archive operation.
 */
export type BulkArchiveResponse = {
    archived_count: number;
};

/**
 * Request to delete multiple items at once.
 */
export type BulkDeleteRequest = {
    item_ids: Array<(string)>;
};

/**
 * Response for bulk delete operation.
 */
export type BulkDeleteResponse = {
    deleted_count: number;
};

/**
 * Request to set categories on multiple items at once.
 */
export type BulkSetCategoriesRequest = {
    item_ids: Array<(string)>;
    category_ids?: Array<(string)>;
};

/**
 * Response for bulk set categories operation.
 */
export type BulkSetCategoriesResponse = {
    updated_count: number;
};

/**
 * Response for bulk unarchive operation.
 */
export type BulkUnarchiveResponse = {
    unarchived_count: number;
};

/**
 * List of categories.
 */
export type CategoriesPublic = {
    data: Array<CategoryPublic>;
    count: number;
};

/**
 * Properties to receive on category creation.
 */
export type CategoryCreate = {
    name: string;
    parent_id?: (string | null);
};

/**
 * API response for a category.
 */
export type CategoryPublic = {
    id: string;
    name: string;
    parent_id: (string | null);
    created_at: string;
};

/**
 * A suggested category.
 */
export type CategorySuggestionPublic = {
    category_id: string;
    category_name: string;
    confidence: number;
    source: string;
};

/**
 * Request for category suggestions.
 */
export type CategorySuggestionRequest = {
    product_url?: (string | null);
    title?: (string | null);
    breadcrumbs?: (Array<(string)> | null);
    brand?: (string | null);
    category?: (string | null);
};

/**
 * Response for category suggestions.
 */
export type CategorySuggestionsPublic = {
    suggestions: Array<CategorySuggestionPublic>;
};

/**
 * Properties to receive on category update.
 */
export type CategoryUpdate = {
    name?: (string | null);
    parent_id?: (string | null);
};

/**
 * Public cooloff settings for viewing shared wishlists.
 *
 * Exposes only timing settings, not balance or rate info.
 */
export type CooloffSettingsPublic = {
    cooloff_scaling_cents?: (number | null);
    cooloff_scaling_days?: number;
    cooloff_min_threshold_cents?: (number | null);
    cooloff_min_threshold_days?: number;
    cooloff_base_days?: number;
    cooloff_max_days?: (number | null);
    freeze_penalty_days?: number;
};

/**
 * Normalized delivery status from 17track.
 */
export type DeliveryStatus = 'not_found' | 'info_received' | 'in_transit' | 'out_for_delivery' | 'delivered' | 'exception' | 'expired';

/**
 * API response for a gifted item.
 */
export type GiftedItemPublic = {
    title: string;
    description?: (string | null);
    price_cents: number;
    image_url?: (string | null);
    product_url?: (string | null);
    id: string;
    owner_id: string;
    added_at: string;
    status: "gifted";
    gifted_at: string;
    bought_by_id: string;
    gifter_display_name?: (string | null);
    gift_message?: (string | null);
    tracking_url?: (string | null);
    is_most_desired?: boolean;
    categories?: Array<CategoryPublic>;
    tracking_number?: (string | null);
    tracking_carrier?: (string | null);
    estimated_delivery_at?: (string | null);
    tracking_synced_at?: (string | null);
    tracking_status?: (DeliveryStatus | null);
    tracking_status_label?: (string | null);
    tracking_events?: Array<TrackingEventPublic>;
};

/**
 * Data when gifting an item to someone.
 */
export type GiftRequest = {
    gift_message?: (string | null);
    gifter_display_name?: (string | null);
    tracking_url?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Generic message response.
 */
export type Message = {
    message: string;
};

/**
 * Request body for password reset.
 */
export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * API response for a notification.
 */
export type NotificationPublic = {
    notification_type: NotificationType;
    title: string;
    message: string;
    id: string;
    user_id: string;
    created_at: string;
    read_at: (string | null);
    payload?: ({
    [key: string]: unknown;
} | null);
};

/**
 * Paginated list of notifications.
 */
export type NotificationsPublic = {
    data: Array<NotificationPublic>;
    count: number;
    unread_count: number;
};

/**
 * Types of notifications.
 */
export type NotificationType = 'gift_received' | 'thank_you' | 'freeze_expiring' | 'budget_milestone' | 'delivery_info_received' | 'delivery_in_transit' | 'delivery_out_for_delivery' | 'delivery_delivered' | 'delivery_exception' | 'delivery_expired' | 'price_drop' | 'price_increase' | 'price_tracking_paused';

/**
 * Request body for URL parsing endpoint.
 */
export type ParseUrlRequest = {
    url: string;
};

/**
 * Response from URL parsing endpoint.
 */
export type ParseUrlResponse = {
    title?: (string | null);
    description?: (string | null);
    image_url?: (string | null);
    price_cents?: (number | null);
    currency?: (string | null);
    source_url: string;
    final_url?: (string | null);
    extraction_method?: (string | null);
    brand?: (string | null);
    category?: (string | null);
    breadcrumbs?: (Array<(string)> | null);
};

export type PrepopulateResponse = {
    items_created: number;
    categories_created: number;
    budget_set: boolean;
    test_user_created: boolean;
    test_user_id: (string | null);
    errors: Array<(string)>;
};

/**
 * Why a check could not be trusted. Drives the one-word UI status.
 */
export type PriceCheckFailureReason = 'blocked' | 'unreachable' | 'no_price' | 'link_moved' | 'different_product' | 'implausible' | 'no_link';

/**
 * Result of a single price check.
 */
export type PriceCheckOutcome = 'unchanged' | 'dropped' | 'increased' | 'failed';

/**
 * Response for a manual price check.
 *
 * Failures are reported inside the body (not as HTTP errors) so the UI can
 * show them inline next to the graph rather than as a generic error toast.
 */
export type PriceCheckResultPublic = {
    outcome: PriceCheckOutcome;
    message: string;
    reason?: (PriceCheckFailureReason | null);
    checked_at: string;
    price_cents?: (number | null);
    previous_price_cents?: (number | null);
    tracking: PriceTrackingPublic;
};

/**
 * Full price history for one item (drawer graph).
 */
export type PriceHistoryPublic = {
    item_id: string;
    current_price_cents: number;
    tracking: PriceTrackingPublic;
    points: Array<PricePointPublic>;
};

/**
 * A single point on the price history graph.
 */
export type PricePointPublic = {
    recorded_at: string;
    price_cents: number;
    source: PricePointSource;
};

/**
 * How a price point was captured.
 */
export type PricePointSource = 'initial' | 'scheduled' | 'manual' | 'added';

/**
 * Tracking state embedded in wishlisted item responses.
 */
export type PriceTrackingPublic = {
    enabled: boolean;
    eligible: boolean;
    paused: boolean;
    disabled_by_user?: boolean;
    last_checked_at?: (string | null);
    last_error?: (string | null);
    last_error_reason?: (PriceCheckFailureReason | null);
    consecutive_failures?: number;
    original_price_cents?: (number | null);
    lowest_price_cents?: (number | null);
    previous_price_cents?: (number | null);
    price_changed_at?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * API response for a purchased item.
 */
export type PurchasedItemPublic = {
    title: string;
    description?: (string | null);
    price_cents: number;
    image_url?: (string | null);
    product_url?: (string | null);
    id: string;
    owner_id: string;
    added_at: string;
    status: "purchased";
    purchased_at: string;
    is_most_desired?: boolean;
    categories?: Array<CategoryPublic>;
    tracking_url?: (string | null);
    actual_price_paid_cents?: (number | null);
    tracking_number?: (string | null);
    tracking_carrier?: (string | null);
    estimated_delivery_at?: (string | null);
    tracking_synced_at?: (string | null);
    tracking_status?: (DeliveryStatus | null);
    tracking_status_label?: (string | null);
    tracking_events?: Array<TrackingEventPublic>;
};

/**
 * Optional data when marking item as purchased.
 */
export type PurchaseRequest = {
    tracking_url?: (string | null);
    actual_price_paid_cents?: (number | null);
    tracking_number?: (string | null);
    tracking_carrier?: (string | null);
};

/**
 * Properties to receive on push subscription creation.
 */
export type PushSubscriptionCreate = {
    endpoint: string;
    p256dh_key: string;
    auth_key: string;
};

/**
 * API response for a push subscription.
 */
export type PushSubscriptionPublic = {
    endpoint: string;
    p256dh_key: string;
    auth_key: string;
    id: string;
    created_at: string;
};

/**
 * JSON payload containing access token.
 */
export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * API response for a tracked item (not from wishlist).
 */
export type TrackedItemPublic = {
    title: string;
    description?: (string | null);
    price_cents: number;
    image_url?: (string | null);
    product_url?: (string | null);
    id: string;
    owner_id: string;
    added_at: string;
    status: "tracking";
    is_most_desired?: boolean;
    categories?: Array<CategoryPublic>;
    tracking_number?: (string | null);
    tracking_carrier?: (string | null);
    tracking_url?: (string | null);
    estimated_delivery_at?: (string | null);
    tracking_synced_at?: (string | null);
    tracking_status?: (DeliveryStatus | null);
    tracking_status_label?: (string | null);
    tracking_events?: Array<TrackingEventPublic>;
};

/**
 * Address information from tracking event.
 */
export type TrackingAddress = {
    country?: (string | null);
    state?: (string | null);
    city?: (string | null);
    postal_code?: (string | null);
};

/**
 * Single tracking event from carrier.
 */
export type TrackingEvent = {
    time_iso?: (string | null);
    time_utc?: (string | null);
    description: string;
    location?: (string | null);
    stage?: (string | null);
    sub_status?: (string | null);
    address?: (TrackingAddress | null);
};

/**
 * Simplified tracking event for public API responses.
 */
export type TrackingEventPublic = {
    timestamp?: (string | null);
    description: string;
    location?: (string | null);
};

/**
 * Request to parse a tracking number or URL.
 */
export type TrackingParseRequest = {
    input: string;
};

/**
 * Response from parsing a tracking input.
 */
export type TrackingParseResponse = {
    tracking_number: string;
    carrier?: (string | null);
    carrier_code?: (number | null);
    is_valid: boolean;
    tracking_url?: (string | null);
};

/**
 * Public tracking status for API responses.
 */
export type TrackingStatusPublic = {
    tracking_number: string;
    carrier?: (string | null);
    status: DeliveryStatus;
    status_label: string;
    estimated_delivery_at?: (string | null);
    latest_event_description?: (string | null);
    latest_event_location?: (string | null);
    latest_event_at?: (string | null);
    events?: Array<TrackingEvent>;
    synced_at?: (string | null);
};

/**
 * Response from sync all tracking operation.
 */
export type TrackingSyncResponse = {
    synced_count: number;
    message: string;
};

/**
 * Where to move an item when undoing purchase/gift.
 */
export type UndoDestination = 'wishlist' | 'archive';

/**
 * Unified request to undo a purchase or gift.
 *
 * Supports flexible handling:
 * - Choose destination (wishlist or archive)
 * - Specify refund amount (None = item price, 0 = no refund, or custom amount)
 */
export type UndoRequest = {
    /**
     * Where to move the item: wishlist or archive
     */
    destination?: UndoDestination;
    /**
     * Amount to refund. None = item price, 0 = no refund, or specify amount
     */
    refund_cents?: (number | null);
    reason?: (string | null);
};

/**
 * Response for unread notification count.
 */
export type UnreadCountPublic = {
    count: number;
};

/**
 * Request body for password update.
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * Properties to receive via API on creation.
 */
export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    wishlist_visibility?: WishlistVisibility;
    password: string;
};

/**
 * User response model for API.
 */
export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    wishlist_visibility?: WishlistVisibility;
    id: string;
};

/**
 * Properties for user self-registration.
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * Paginated list of users.
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * Properties to receive via API on update, all are optional.
 */
export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    wishlist_visibility?: WishlistVisibility;
    password?: (string | null);
};

/**
 * Properties for user to update their own profile.
 */
export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    wishlist_visibility?: (WishlistVisibility | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

/**
 * API response for VAPID public key.
 */
export type VapidKeyPublic = {
    public_key: (string | null);
    enabled: boolean;
};

/**
 * Request to waive cooldown period on a wishlist item.
 */
export type WaiveCooldownRequest = {
    reason: string;
};

/**
 * API response for a wishlisted item.
 */
export type WishlistedItemPublic = {
    title: string;
    description?: (string | null);
    price_cents: number;
    image_url?: (string | null);
    product_url?: (string | null);
    id: string;
    owner_id: string;
    added_at: string;
    status: "wishlisted";
    is_most_desired?: boolean;
    categories?: Array<CategoryPublic>;
    cooldown_waived_at?: (string | null);
    price_tracking?: (PriceTrackingPublic | null);
};

/**
 * Properties to receive on wishlist item creation.
 */
export type WishlistItemCreate = {
    title: string;
    description?: (string | null);
    price_cents: number;
    image_url?: (string | null);
    product_url?: (string | null);
    category_ids?: Array<(string)>;
    tracking_number?: (string | null);
    tracking_carrier?: (string | null);
    tracking_url?: (string | null);
    price_from_url?: boolean;
};

/**
 * Paginated list of wishlist items.
 */
export type WishlistItemsPublic = {
    data: Array<(WishlistedItemPublic | PurchasedItemPublic | GiftedItemPublic | ArchivedItemPublic | TrackedItemPublic)>;
    count: number;
};

/**
 * Properties to receive on wishlist item update.
 */
export type WishlistItemUpdate = {
    title?: (string | null);
    description?: (string | null);
    price_cents?: (number | null);
    image_url?: (string | null);
    product_url?: (string | null);
    category_ids?: (Array<(string)> | null);
    tracking_number?: (string | null);
    tracking_carrier?: (string | null);
    tracking_url?: (string | null);
};

/**
 * Properties to receive on wishlist share creation.
 */
export type WishlistShareCreate = {
    shared_with_email: string;
};

/**
 * API response for a wishlist share.
 */
export type WishlistSharePublic = {
    id: string;
    owner_id: string;
    shared_with_id: string;
    shared_with_email: string;
    owner_email: string;
    created_at: string;
};

/**
 * Paginated list of wishlist shares.
 */
export type WishlistSharesPublic = {
    data: Array<WishlistSharePublic>;
    count: number;
};

/**
 * Visibility setting for a user's wishlist.
 */
export type WishlistVisibility = 'private' | 'public';

/**
 * Wishlist items with owner's cooloff settings for shared wishlist viewing.
 */
export type WishlistWithSettingsPublic = {
    data: Array<(WishlistedItemPublic | PurchasedItemPublic | GiftedItemPublic | ArchivedItemPublic | TrackedItemPublic)>;
    count: number;
    owner_cooloff_settings: CooloffSettingsPublic;
};

export type BudgetGetBudgetResponse = (BudgetPublic);

export type BudgetUpdateBudgetData = {
    requestBody: BudgetUpdate;
};

export type BudgetUpdateBudgetResponse = (BudgetPublic);

export type BudgetUnfreezeBudgetResponse = (BudgetPublic);

export type CategoriesReadCategoriesResponse = (CategoriesPublic);

export type CategoriesCreateNewCategoryData = {
    requestBody: CategoryCreate;
};

export type CategoriesCreateNewCategoryResponse = (CategoryPublic);

export type CategoriesReadCategoryData = {
    categoryId: string;
};

export type CategoriesReadCategoryResponse = (CategoryPublic);

export type CategoriesUpdateCategoryEndpointData = {
    categoryId: string;
    requestBody: CategoryUpdate;
};

export type CategoriesUpdateCategoryEndpointResponse = (CategoryPublic);

export type CategoriesDeleteCategoryEndpointData = {
    categoryId: string;
};

export type CategoriesDeleteCategoryEndpointResponse = (Message);

export type CategoriesGetCategorySuggestionsData = {
    requestBody: CategorySuggestionRequest;
};

export type CategoriesGetCategorySuggestionsResponse = (CategorySuggestionsPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type NotificationsListNotificationsData = {
    limit?: number;
    offset?: number;
};

export type NotificationsListNotificationsResponse = (NotificationsPublic);

export type NotificationsReadUnreadCountResponse = (UnreadCountPublic);

export type NotificationsMarkNotificationReadData = {
    notificationId: string;
};

export type NotificationsMarkNotificationReadResponse = (NotificationPublic);

export type NotificationsMarkAllNotificationsReadResponse = (Message);

export type PriceTrackingReadPriceHistoryData = {
    itemId: string;
};

export type PriceTrackingReadPriceHistoryResponse = (PriceHistoryPublic);

export type PriceTrackingEnablePriceTrackingData = {
    itemId: string;
};

export type PriceTrackingEnablePriceTrackingResponse = (WishlistedItemPublic);

export type PriceTrackingDisablePriceTrackingData = {
    itemId: string;
};

export type PriceTrackingDisablePriceTrackingResponse = (WishlistedItemPublic);

export type PriceTrackingRestartPriceTrackingData = {
    itemId: string;
};

export type PriceTrackingRestartPriceTrackingResponse = (WishlistedItemPublic);

export type PriceTrackingCheckPriceNowData = {
    itemId: string;
};

export type PriceTrackingCheckPriceNowResponse = (PriceCheckResultPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type PrivatePrepopulateTestDataResponse = (PrepopulateResponse);

export type PushGetVapidKeyResponse = (VapidKeyPublic);

export type PushSubscribeToPushData = {
    requestBody: PushSubscriptionCreate;
};

export type PushSubscribeToPushResponse = (PushSubscriptionPublic);

export type PushUnsubscribeFromPushData = {
    endpoint: string;
};

export type PushUnsubscribeFromPushResponse = (Message);

export type SharesReadMySharesResponse = (WishlistSharesPublic);

export type SharesCreateNewShareData = {
    requestBody: WishlistShareCreate;
};

export type SharesCreateNewShareResponse = (WishlistSharePublic);

export type SharesReadSharesWithMeResponse = (WishlistSharesPublic);

export type SharesDeleteShareEndpointData = {
    shareId: string;
};

export type SharesDeleteShareEndpointResponse = (Message);

export type TrackingParseTrackingData = {
    requestBody: TrackingParseRequest;
};

export type TrackingParseTrackingResponse = (TrackingParseResponse);

export type TrackingListTrackedItemsResponse = (WishlistItemsPublic);

export type TrackingGetTrackingStatusData = {
    itemId: string;
};

export type TrackingGetTrackingStatusResponse = (TrackingStatusPublic);

export type TrackingSyncTrackingData = {
    itemId: string;
};

export type TrackingSyncTrackingResponse = (TrackingStatusPublic);

export type TrackingSyncAllTrackingResponse = (TrackingSyncResponse);

export type UrlParserParseProductUrlData = {
    requestBody: ParseUrlRequest;
};

export type UrlParserParseProductUrlResponse = (ParseUrlResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserEndpointData = {
    requestBody: UserCreate;
};

export type UsersCreateUserEndpointResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserEndpointData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserEndpointResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WishlistReadWishlistItemsData = {
    limit?: number;
    skip?: number;
};

export type WishlistReadWishlistItemsResponse = (WishlistItemsPublic);

export type WishlistCreateItemData = {
    requestBody: WishlistItemCreate;
};

export type WishlistCreateItemResponse = ((WishlistedItemPublic | TrackedItemPublic));

export type WishlistReadUserWishlistData = {
    limit?: number;
    skip?: number;
    userId: string;
};

export type WishlistReadUserWishlistResponse = (WishlistWithSettingsPublic);

export type WishlistReadWishlistItemData = {
    itemId: string;
};

export type WishlistReadWishlistItemResponse = ((WishlistedItemPublic | PurchasedItemPublic | GiftedItemPublic | ArchivedItemPublic | TrackedItemPublic));

export type WishlistUpdateItemData = {
    itemId: string;
    requestBody: WishlistItemUpdate;
};

export type WishlistUpdateItemResponse = ((WishlistedItemPublic | PurchasedItemPublic | GiftedItemPublic | ArchivedItemPublic | TrackedItemPublic));

export type WishlistDeleteItemData = {
    itemId: string;
};

export type WishlistDeleteItemResponse = (Message);

export type WishlistBulkDeleteItemsEndpointData = {
    requestBody: BulkDeleteRequest;
};

export type WishlistBulkDeleteItemsEndpointResponse = (BulkDeleteResponse);

export type WishlistBulkSetCategoriesEndpointData = {
    requestBody: BulkSetCategoriesRequest;
};

export type WishlistBulkSetCategoriesEndpointResponse = (BulkSetCategoriesResponse);

export type WishlistBulkArchiveItemsEndpointData = {
    requestBody: BulkArchiveRequest;
};

export type WishlistBulkArchiveItemsEndpointResponse = (BulkArchiveResponse);

export type WishlistBulkUnarchiveItemsEndpointData = {
    requestBody: BulkArchiveRequest;
};

export type WishlistBulkUnarchiveItemsEndpointResponse = (BulkUnarchiveResponse);

export type WishlistPurchaseItemData = {
    itemId: string;
    requestBody?: (PurchaseRequest | null);
};

export type WishlistPurchaseItemResponse = (PurchasedItemPublic);

export type WishlistUndoItemEndpointData = {
    itemId: string;
    requestBody: UndoRequest;
};

export type WishlistUndoItemEndpointResponse = ((WishlistedItemPublic | ArchivedItemPublic));

export type WishlistWaiveCooldownData = {
    itemId: string;
    requestBody: WaiveCooldownRequest;
};

export type WishlistWaiveCooldownResponse = (WishlistedItemPublic);

export type WishlistGetItemCategoriesData = {
    itemId: string;
};

export type WishlistGetItemCategoriesResponse = (CategoriesPublic);

export type WishlistAddCategoriesToItemEndpointData = {
    itemId: string;
    requestBody: AddCategoriesRequest;
};

export type WishlistAddCategoriesToItemEndpointResponse = (CategoriesPublic);

export type WishlistRemoveCategoryFromItemEndpointData = {
    categoryId: string;
    itemId: string;
};

export type WishlistRemoveCategoryFromItemEndpointResponse = (Message);

export type WishlistToggleMostDesiredEndpointData = {
    itemId: string;
};

export type WishlistToggleMostDesiredEndpointResponse = ((WishlistedItemPublic | PurchasedItemPublic));

export type WishlistGiftItemData = {
    itemId: string;
    requestBody?: (GiftRequest | null);
};

export type WishlistGiftItemResponse = (GiftedItemPublic);