"""Add archived_at field

Revision ID: 011a1e4cad39
Revises: d2e9c3e48ad0
Create Date: 2026-01-15 01:20:59.586440

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '011a1e4cad39'
down_revision = 'd2e9c3e48ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlistitem', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlistitem', 'archived_at')
    # ### end Alembic commands ###
