"""add cooldown waiver field

Revision ID: 18c81d2a00b6
Revises: 3d7060741828
Create Date: 2026-01-25 16:36:22.278066

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '18c81d2a00b6'
down_revision = '3d7060741828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlistitem', sa.Column('cooldown_waived_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlistitem', 'cooldown_waived_at')
    # ### end Alembic commands ###
