"""add_gifted_status_and_gift_fields

Revision ID: 3198ee268c3d
Revises: 81a086c292d7
Create Date: 2026-01-20 23:36:56.628540

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3198ee268c3d'
down_revision = '81a086c292d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlistitem', sa.Column('bought_by_id', sa.Uuid(), nullable=True))
    op.add_column('wishlistitem', sa.Column('gift_message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('wishlistitem', sa.Column('gifter_display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('wishlistitem', sa.Column('gifted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'wishlistitem', 'user', ['bought_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlistitem', type_='foreignkey')
    op.drop_column('wishlistitem', 'gifted_at')
    op.drop_column('wishlistitem', 'gifter_display_name')
    op.drop_column('wishlistitem', 'gift_message')
    op.drop_column('wishlistitem', 'bought_by_id')
    # ### end Alembic commands ###
