"""Add tracking notification types

Revision ID: 3d7060741828
Revises: 8a6cbc018be0
Create Date: 2026-01-24 10:52:03.123318

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = '3d7060741828'
down_revision = '8a6cbc018be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='notificationtype',
        new_values=['GIFT_RECEIVED', 'THANK_YOU', 'FREEZE_EXPIRING', 'BUDGET_MILESTONE', 'DELIVERY_INFO_RECEIVED', 'DELIVERY_IN_TRANSIT', 'DELIVERY_OUT_FOR_DELIVERY', 'DELIVERY_DELIVERED', 'DELIVERY_EXCEPTION', 'DELIVERY_EXPIRED'],
        affected_columns=[TableReference(table_schema='public', table_name='notification', column_name='notification_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='notificationtype',
        new_values=['GIFT_RECEIVED', 'THANK_YOU', 'FREEZE_EXPIRING', 'BUDGET_MILESTONE'],
        affected_columns=[TableReference(table_schema='public', table_name='notification', column_name='notification_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
