"""Add push subscription table

Revision ID: 7c6095766c76
Revises: dc48fc01df10
Create Date: 2026-01-21 18:56:02.634973

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7c6095766c76'
down_revision = 'dc48fc01df10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pushsubscription',
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('p256dh_key', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('auth_key', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pushsubscription_endpoint'), 'pushsubscription', ['endpoint'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pushsubscription_endpoint'), table_name='pushsubscription')
    op.drop_table('pushsubscription')
    # ### end Alembic commands ###
