"""add_tracking_url_and_actual_price_to_wishlist_item

Revision ID: 81a086c292d7
Revises: b3971e039dc8
Create Date: 2026-01-20 23:28:58.161841

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '81a086c292d7'
down_revision = 'b3971e039dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlistitem', sa.Column('tracking_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True))
    op.add_column('wishlistitem', sa.Column('actual_price_paid_cents', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlistitem', 'actual_price_paid_cents')
    op.drop_column('wishlistitem', 'tracking_url')
    # ### end Alembic commands ###
