"""add_tracking_status_and_fields

Revision ID: 8a6cbc018be0
Revises: 7c6095766c76
Create Date: 2026-01-23 23:35:45.619701

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = '8a6cbc018be0'
down_revision = '7c6095766c76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlistitem', sa.Column('tracking_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('wishlistitem', sa.Column('tracking_carrier', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('wishlistitem', sa.Column('tracking_data', sa.JSON(), nullable=True))
    op.add_column('wishlistitem', sa.Column('tracking_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('wishlistitem', sa.Column('estimated_delivery_at', sa.DateTime(timezone=True), nullable=True))
    op.sync_enum_values(
        enum_schema='public',
        enum_name='wishlistitemstatus',
        new_values=['WISHLISTED', 'PURCHASED', 'GIFTED', 'ARCHIVED', 'TRACKING'],
        affected_columns=[TableReference(table_schema='public', table_name='wishlistitem', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='wishlistitemstatus',
        new_values=['WISHLISTED', 'PURCHASED', 'GIFTED', 'ARCHIVED'],
        affected_columns=[TableReference(table_schema='public', table_name='wishlistitem', column_name='status')],
        enum_values_to_rename=[],
    )
    op.drop_column('wishlistitem', 'estimated_delivery_at')
    op.drop_column('wishlistitem', 'tracking_synced_at')
    op.drop_column('wishlistitem', 'tracking_data')
    op.drop_column('wishlistitem', 'tracking_carrier')
    op.drop_column('wishlistitem', 'tracking_number')
    # ### end Alembic commands ###
