"""Add undo_reason and undone_at to wishlist_item

Revision ID: 9852c8d2221a
Revises: 35b54d427a12
Create Date: 2026-01-13 13:40:19.649970

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9852c8d2221a'
down_revision = '35b54d427a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlistitem', sa.Column('undo_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('wishlistitem', sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlistitem', 'undone_at')
    op.drop_column('wishlistitem', 'undo_reason')
    # ### end Alembic commands ###
