"""add_is_most_desired_to_wishlistitem

Revision ID: b3971e039dc8
Revises: c774c628e6aa
Create Date: 2026-01-19 17:11:00.403207

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b3971e039dc8'
down_revision = 'c774c628e6aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlistitem', sa.Column('is_most_desired', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlistitem', 'is_most_desired')
    # ### end Alembic commands ###
