"""Add wishlist visibility and sharing

Revision ID: cf09385e454f
Revises: 9852c8d2221a
Create Date: 2026-01-14 14:23:02.519026

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cf09385e454f'
down_revision = '9852c8d2221a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    # Create enum type for PostgreSQL only; SQLite stores enums as strings
    if bind.dialect.name == "postgresql":
        wishlist_visibility_enum = sa.Enum('PRIVATE', 'PUBLIC', name='wishlistvisibility')
        wishlist_visibility_enum.create(bind, checkfirst=True)
        visibility_type = wishlist_visibility_enum
    else:
        visibility_type = sa.String(50)

    op.create_table('wishlistshare',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('shared_with_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'shared_with_id', name='unique_share')
    )
    op.add_column('user', sa.Column('wishlist_visibility', visibility_type, nullable=False, server_default='PRIVATE'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    op.drop_column('user', 'wishlist_visibility')
    op.drop_table('wishlistshare')
    # Drop the enum type (PostgreSQL only)
    if bind.dialect.name == "postgresql":
        sa.Enum(name='wishlistvisibility').drop(bind, checkfirst=True)
    # ### end Alembic commands ###
