"""add_gifted_status_to_wishlistitemstatus_enum

Revision ID: dc48fc01df10
Revises: f7f14b784d74
Create Date: 2026-01-21 13:53:32.398605

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = 'dc48fc01df10'
down_revision = 'f7f14b784d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='wishlistitemstatus',
        new_values=['WISHLISTED', 'PURCHASED', 'GIFTED', 'ARCHIVED'],
        affected_columns=[TableReference(table_schema='public', table_name='wishlistitem', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='wishlistitemstatus',
        new_values=['WISHLISTED', 'PURCHASED', 'ARCHIVED'],
        affected_columns=[TableReference(table_schema='public', table_name='wishlistitem', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
